final url = 'http://localhost:3000';
final registration = url + "/registration";
final login = url + '/login';
final gotoProfile = url + '/gotoProfile';
final updateDetails = url + '/updateDetails';
final addtodo = url + '/todo/createToDo';
final getToDoList = url + '/todo/getUserTodoList';
final deleteTodo = url + '/todo/deleteTodo';
final EditToDo = url + '/todo/EditToDo';
